# Generated by Django 4.2.5 on 2023-09-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.IntegerField(verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('authors', models.CharField(max_length=255, verbose_name='authors')),
                ('category', models.CharField(max_length=255, verbose_name='category')),
                ('subtitle', models.FloatField(verbose_name='distribution_expense')),
                ('published_date', models.DateField(auto_now=True, verbose_name='published_date')),
            ],
        ),
    ]
