# Generated by Django 4.2.5 on 2023-09-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_book_bookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='distribution_expense',
            field=models.FloatField(default=0, verbose_name='distribution_expense'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='subtitle'),
        ),
    ]
